### ISSUE TITLE
Unhandled exception of type 'System.Data.Entity.Core.ProviderIncompatibleException'

### ISSUE THREAD

**Issue by ghost** [hilts-vaughan/OpenORPG#10]
This happens while in the editor. Not sure the root cause of how to reproduce though.

Happens on this line:
List<UserAccount> accounts = context.Accounts.Where(x => x.IsOnline).ToList();

More information:
https://dl.dropboxusercontent.com/u/67149765/OpenORPG/Error1.txt
http://i.imgur.com/NGlzw0w.png

**Comment by ghost** [comment]
I believe it is the server actually... My bad.

**Comment by hilts-vaughan** [comment]
This isn't  a bug.

"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)"

Please configure your MySQL server correctly and try again.

**Comment by suirad** [comment]
There still needs to be some documentation on how to properly setup the DB for the server

**Comment by hilts-vaughan** [comment]
It's just an Entity Framework string -- although, agreed. I should update the wiki on this.

In the meanwhile, just check out the "App.config" file in the server projector and you should be able to figure it out (change the host, password, username). If for any reason you can't / it does not work, please leave a comment or get in touch

**Comment by suirad** [comment]
Ah okay i figured it out. I had to change the sql string in the app.config. After that i went into my server and manually created the orpg database. That's what the problem was for me. I removed the manually created db and reloaded the server. It created the database no problem after that.

**Comment by hilts-vaughan** [comment]
Odd, I'll check a fresh install in a virtual machine and make sure fresh
copies work without a hitch from now on. Sounds like a bug with the Entity
Framework class DropCreateDatabaseIfModelChanges.
