### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by BruceJohnJennerLawso** [hilts-vaughan/OpenORPG#11]
I dont see any releases, do I need to build the project in order to try it out?

**Comment by ghost** [comment]
Yes, the build setup is pretty straight forward. It can be setup in literally 5-10 minutes. If you get stuck, I can guide you on the steps you may have missed. 

Go here. https://github.com/hilts-vaughan/OpenORPG/wiki

**Comment by hilts-vaughan** [comment]
Closing. Build steps are provided, if anyone has issues in the future please re open an issue.
