### ISSUE TITLE
State of this framework?

### ISSUE THREAD

**Issue by L0G1C** [hilts-vaughan/OpenORPG#28]
Hello,

i'm a hobbyist gamedev with some background in C#/unity in making games and I've been doing a ton of research all day in looking to do a phaser-based RPG game on the web with a client-server authoritative architecture. I landed here through all my searching and it looks EXACTLY like what I was getting ready to start writing out by hand. Just curious what the state of the development is? Are people still actively working on improvements? I hope to contribute as I get familiar with things.

**Comment by hilts-vaughan** [comment]
Hi,

The state of things is a bit rough but usable. You can certainly write a
basic game without too much trouble. Active development? No, definitely not
as its worked on as a on-need basis. That said, if you need help setting
things up or require features for your own project, please drop me a line
and I can see if OpenORPG is right for you.

**Comment by hilts-vaughan** [comment]
I _SHOULD_ be more clear, though. As you can see, there are pull requests sitting in the queue. If you're working towards something and we share some goals, join in on some issues, connect with the rest of us, and we'd welcome any contributions or suggestions you have!

**Comment by L0G1C** [comment]
only issue i see so far is when following this guide https://github.com/hilts-vaughan/OpenORPG/wiki/Setup-Guide-for-Development
  I'm getting a number of typescript errors, most of which have to do with jquery or jqueryui. Is there a specific version of typescript I should use?

**Comment by L0G1C** [comment]
Here's my error list. It just seems like the definition types aren't working? I'm not too familiar with typescript yet. any tips?
![capture](https://cloud.githubusercontent.com/assets/1203115/12409396/8e0eeb7c-be37-11e5-8531-116a2f16845f.JPG)

I also noticed that on that setup guide in the wiki, the bottom picture for web configuration for typescript is not showing up.

**Comment by L0G1C** [comment]
UPDATE: I got it to build by updating the jquery.d.ts and jqueryui.d.ts files. but i'm afraid to run it because of what I said earlier about the picture for the configuration for the wbe project not being on the setup guide!

**Comment by hilts-vaughan** [comment]
Hi there,

What version of everything are you using (including the TypeScript compiler). I have a hunch that things have changed drastically.

**Comment by L0G1C** [comment]
I just went and got everything this weekend so typescript would be version 1.7.5 and phaser 2.4.4

**Comment by L0G1C** [comment]
I have the solution building and the database was pointed to my local SQL server and created all of the objects. The only error i'm getting is "An attempt was made to access socket in a way forbidden by its access permissions" when it tries to start the WebSocket Server in NetworkManager.cs Any tips?

During this process I am seeing the "connecting to server" sprite and stuff in the browser.

**Comment by hilts-vaughan** [comment]
This points to a database error. You edited your app.config to point accordingly, right? What SQL server are you using? It should in theory work with ANY Entity Framework supported DB but I've only _TESTED_ MariaDB / MySQL.

**Comment by L0G1C** [comment]
Yes I updated the app.config to point to SQL instead of MySQL, just to get it running, as I'm not too familiar with MySQL. There were several things to change tho, so I might have missed some line. I'll see if I can find it. :+1:
