### ISSUE TITLE
Chat Box Dummy Text Visibility

### ISSUE THREAD

**Issue by ghost** [hilts-vaughan/OpenORPG#6]
The default text on the chat box does not disappear after the chat box receives focus. It should of course be put back after losing focus, but it should lose visibility upon receiving focus.

**Comment by hilts-vaughan** [comment]
I won't fix this -- it's the W3C standard. You have a text caret in place that can demonstrate your box is active. If you disagree, feel free to raise the issue. Closing.

**Comment by ghost** [comment]
Yeah, I am aware of that standard, but that is generally for websites not games.
